name: Generate Readme and Release Action #
description: 'Builds an image, pushes to artifact registry, and caches to gha as well as the `cache` tag'
inputs:
  token:
    description: 'git token to use for the run'
    required: false
    default: "derp"
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "${{ inputs.token }} is: ${{ inputs.token }}"
    - shell: bash
      run: |
        if [ "$GITHUB_TOKEN" = "${{ github.token }}" ]; then
            echo "$GITHUB_TOKEN and ${{ github.token }} are equal"
        else
            echo "$GITHUB_TOKEN and ${{ github.token }} are not equal"
        fi
    - shell: bash
      run: |
        if [ "$GITHUB_TOKEN" = "${{ inputs.token }}" ]; then
            echo "$GITHUB_TOKEN and input token are equal"
        else
            echo "GITHUB_TOKEN and input token are not equal"
        fi
    - name: Test credentials
      shell: bash
      run: |
        echo "stuff" > derp1.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
#    - name: Dry run to get next version
#      id: semantic-release-dry-run
#      uses: cycjimmy/semantic-release-action@v2
#      with:
#        dry_run: true
#        extends: |
#          @swarm-io/release-config-actions
#      env:
#        # github.token can't trigger workflows, we want the created release to trigger other workflows, so use the runner token
#        GITHUB_TOKEN: ${{ inputs.token }}
#    - uses: bitflight-devops/github-action-readme-generator@v1.0.12a
#      with:
#        action: ${{ github.workspace }}/action.yaml
#        owner: ${{ github.repository_owner }}
#        repo: ${{ github.event.repository.name }}
#        pretty: true
#        versioning_enabled: true
#        version_override: v${{ steps.semantic-release-dry-run.outputs.new_release_major_version }}
#    - uses: stefanzweifel/git-auto-commit-action@v4
#      with:
#        branch: main
#    - id: semantic-release
#      uses: cycjimmy/semantic-release-action@v2
#      with:
#        extends: |
#          @swarm-io/release-config-actions
#      env:
#        # github.token can't trigger workflows, we want the created release to trigger other workflows, so use the runner token
#        GITHUB_TOKEN: ${{ inputs.token }}