name: Generate Readme and Release Action #
description: 'Builds an image, pushes to artifact registry, and caches to gha as well as the `cache` tag'
inputs:
  token:
    description: 'git token to use for the run'
    required: true
  toggle-admins:
    description: 'If true, this action will disable the `include administrators` setting in branch protection for this branch, and re-enable it after release. Re-enabling is run using always()'
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - shell: bash
      run: |
        echo "stuff" >> derp.txt
    - uses: swarm-io/action-branch-protection-bot@init
      if: inputs.toggle-admins
      with:
        token: ${{ inputs.token }}
        include-admins: false
    - uses: stefanzweifel/git-auto-commit-action@v4
    - uses: swarm-io/action-branch-protection-bot@init
      if: inputs.toggle-admins && always()  # Force to always run this step to ensure "include administrators" is always turned back on
      with:
        token: ${{ inputs.token }}
        include-admins: true
#    - name: Dry run to get next version
#      id: semantic-release-dry-run
#      uses: cycjimmy/semantic-release-action@v2
#      with:
#        dry_run: true
#        extends: |
#          @swarm-io/release-config-actions
#    - uses: bitflight-devops/github-action-readme-generator@v1.0.12a
#      with:
#        action: ${{ github.workspace }}/action.yaml
#        owner: ${{ github.repository_owner }}
#        repo: ${{ github.event.repository.name }}
#        pretty: true
#        versioning_enabled: true
#        version_override: v${{ steps.semantic-release-dry-run.outputs.new_release_major_version }}
#    - id: semantic-release
#      uses: cycjimmy/semantic-release-action@v2
#      with:
#        extends: |
#          @swarm-io/release-config-actions