name: Semantic Release
on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main
#    paths:
#      - action.yaml
  push:
    branches:
      - main
jobs:
  semantic-release:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: swarm-io/action-release-action@main